-- ============================================
-- PROYECTO web — BASE DE DATOS (MÓDULOS 1-5)
-- Versión final corregida — 26/08/2026 (integridad reforzada, base Codex + parche)
-- ============================================
-- CORRECCIÓN ADICIONAL SOBRE LA BASE DE CODEX:
--  17. incidencias: trigger_validar_reportante_incidencia se disparaba en
--      CUALQUIER UPDATE de la fila, bloqueando ediciones (ej. corregir un
--      texto) una vez que el seguimiento pasaba a 'cerrado'. Ahora solo se
--      dispara al crear la incidencia o al reasignar seguimiento/reportante.
--  18. visitas_seguimiento: mismo ajuste que el punto 17, aplicado a
--      trigger_validar_visita_seguimiento. Ya no revalida la asignación del
--      caso al editar observaciones/estado_salud/fecha_realizada/estado.
--
-- CORRECCIONES APLICADAS EN ESTA VERSIÓN:
--  1. mascotas.especie: CHECK restringido a 'perro'/'gato'
--  2. mascotas.edad: ahora NOT NULL (evita bug en vista mascotas_con_rango)
--  3. incidencias: trigger que exige que quien atiende (atendida_por) sea
--     administrador, o el voluntario asignado al caso, y esté activo
--  4. solicitudes_adopcion: trigger que exige que el solicitante sea
--     rol 'ciudadano' y tenga cuenta activa
--  5. visitas_seguimiento: CHECK de cronología, fecha_realizada no puede
--     ser anterior a fecha_programada
--  6. CHECK de texto no vacío (btrim <> '') en: usuarios.nombres/apellidos,
--     mascotas.nombre, solicitudes_adopcion.zona_aproximada/horario_preferido,
--     seguimientos_adopcion.zona_aproximada/horario_preferido,
--     incidencias.descripcion/comentarios_resolucion
--  7. fotos_mascota: índice único (mascota_id, orden) para tipo='foto',
--     evita ambigüedad sobre cuál foto mostrar primero
--  8. postulaciones_voluntariado: quien revisa debe ser administrador activo
--  9. usuarios/voluntarios: no permite desactivar o cambiar el rol de un
--     voluntario mientras su perfil siga activo
-- 10. incidencias: al cambiar de seguimiento se revalida atendida_por
-- 11. Orden del script: las funciones que dependen de tablas de otros módulos
--     se definen después de que esas tablas ya fueron creadas.
-- 12. Dependencias cruzadas principales: solicitudes -> seguimientos y
--     usuarios/voluntarios -> seguimientos se crean después de sus tablas.
-- 13. solicitudes_adopcion: toda fila nueva debe iniciar en 'pendiente'.
-- 14. seguimientos_adopcion: solo puede existir para una solicitud 'aceptada'.
-- 15. voluntarios: FK compuesta garantiza que postulacion_id y usuario_id
--     correspondan al mismo usuario.
--
-- IMPORTANTE: este script crea una instalación nueva. No lo ejecutes de nuevo
-- sobre una base con datos: contiene CREATE TABLE, índices y triggers sin DROP.
-- ============================================

-- ============================================
-- EXTENSIÓN PARA CORREO CASE-INSENSITIVE
-- ============================================

CREATE EXTENSION IF NOT EXISTS citext;

-- ============================================
-- MÓDULO 1 — GESTIÓN DE USUARIOS
-- Tabla: usuarios
-- ============================================

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo CITEXT NOT NULL,
    telefono VARCHAR(20),
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'ciudadano',
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified_at TIMESTAMPTZ NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_correo_unico UNIQUE (correo),
    CONSTRAINT usuarios_correo_no_vacio
        CHECK (btrim(correo::text) <> ''),
    CONSTRAINT usuarios_password_no_vacio
        CHECK (btrim(password) <> ''),
    -- SEGURIDAD / INTEGRIDAD: el teléfono es opcional, pero no puede ser solo espacios.
    CONSTRAINT usuarios_telefono_no_vacio
        CHECK (telefono IS NULL OR btrim(telefono) <> ''),
    CONSTRAINT usuarios_rol_valido
        CHECK (rol IN ('administrador', 'voluntario', 'ciudadano')),

    -- CORRECCIÓN: evita nombres/apellidos en blanco (NOT NULL no lo evita)
    CONSTRAINT usuarios_nombres_no_vacio
        CHECK (btrim(nombres) <> ''),
    CONSTRAINT usuarios_apellidos_no_vacio
        CHECK (btrim(apellidos) <> '')
);

-- Índice para búsquedas frecuentes por rol
CREATE INDEX idx_usuarios_rol ON usuarios(rol);

-- Función y trigger para mantener updated_at actualizado automáticamente
CREATE OR REPLACE FUNCTION actualizar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_usuarios_updated_at
BEFORE UPDATE ON usuarios
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();


-- ============================================
-- MÓDULO 2 — GESTIÓN DE ADOPCIONES (PARTE 1)
-- Tablas: mascotas, fotos_mascota
-- ============================================

-- ============================================
-- 1. Tabla mascotas (COMPLETA CON TAMAÑO)
-- ============================================

CREATE TABLE mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(100) NOT NULL,
    especie VARCHAR(50) NOT NULL,                   -- FILTRO (solo perro/gato)
    raza VARCHAR(100),                              -- INFORMATIVO (NO FILTRO)
    edad SMALLINT NOT NULL CHECK (edad >= 0),       -- FILTRO (con rangos) — CORRECCIÓN: ahora obligatoria
    sexo VARCHAR(10) NOT NULL,                      -- FILTRO
    color VARCHAR(50),                              -- INFORMATIVO (NO FILTRO)
    tamano VARCHAR(20) NOT NULL,                    -- FILTRO
    descripcion TEXT,

    estado VARCHAR(20) NOT NULL DEFAULT 'borrador',

    -- RESTRICT conserva la trazabilidad de quién registró la mascota.
    registrado_por BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT mascotas_sexo_valido
        CHECK (sexo IN ('macho', 'hembra')),

    CONSTRAINT mascotas_estado_valido
        CHECK (estado IN ('borrador', 'disponible', 'adoptada')),

    CONSTRAINT mascotas_tamano_valido
        CHECK (tamano IN ('pequeno', 'mediano', 'grande')),

    -- CORRECCIÓN: el sistema solo maneja perros y gatos
    CONSTRAINT mascotas_especie_valida
        CHECK (especie IN ('perro', 'gato')),

    -- CORRECCIÓN: evita nombre de mascota en blanco
    CONSTRAINT mascotas_nombre_no_vacio
        CHECK (btrim(nombre) <> '')
);

CREATE INDEX idx_mascotas_estado
    ON mascotas(estado);

CREATE INDEX idx_mascotas_especie
    ON mascotas(especie);

CREATE INDEX idx_mascotas_tamano
    ON mascotas(tamano);

CREATE INDEX idx_mascotas_sexo
    ON mascotas(sexo);

-- Índice de la FK usada para trazabilidad y operaciones sobre usuarios.
CREATE INDEX idx_mascotas_registrado_por
    ON mascotas(registrado_por);

-- Reutiliza la función creada en el módulo Usuarios.
CREATE TRIGGER trigger_mascotas_updated_at
BEFORE UPDATE ON mascotas
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();


-- ============================================
-- 2. Tabla fotos_mascota
-- Admite hasta 4 fotos y 1 video opcional.
-- ============================================

CREATE TABLE fotos_mascota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mascota_id BIGINT NOT NULL
        REFERENCES mascotas(id)
        ON DELETE CASCADE,

    tipo VARCHAR(10) NOT NULL DEFAULT 'foto',

    url VARCHAR(255) NOT NULL,

    es_principal BOOLEAN NOT NULL DEFAULT FALSE,

    orden SMALLINT NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fotos_mascota_tipo_valido
        CHECK (tipo IN ('foto', 'video')),

    CONSTRAINT fotos_mascota_url_no_vacia
        CHECK (btrim(url) <> ''),

    CONSTRAINT fotos_mascota_orden_valido
        CHECK (orden > 0),

    -- Un video no puede ser la imagen principal.
    CONSTRAINT fotos_mascota_principal_solo_foto
        CHECK (tipo = 'foto' OR es_principal = FALSE)
);

CREATE INDEX idx_fotos_mascota_mascota_id
    ON fotos_mascota(mascota_id);

-- Cada mascota puede tener una sola foto principal.
CREATE UNIQUE INDEX idx_una_foto_principal_por_mascota
    ON fotos_mascota(mascota_id)
    WHERE tipo = 'foto'
      AND es_principal = TRUE;

-- Cada mascota puede tener un solo video.
CREATE UNIQUE INDEX idx_un_video_por_mascota
    ON fotos_mascota(mascota_id)
    WHERE tipo = 'video';

-- CORRECCIÓN: dos fotos de la misma mascota no pueden compartir el mismo orden
-- (evita ambigüedad sobre cuál mostrar primero).
CREATE UNIQUE INDEX idx_orden_unico_por_mascota
    ON fotos_mascota(mascota_id, orden)
    WHERE tipo = 'foto';


-- ============================================
-- 3. Trigger: máximo 4 fotos y 1 video
-- ============================================

CREATE OR REPLACE FUNCTION validar_limite_multimedia()
RETURNS TRIGGER AS $$
DECLARE
    cantidad INTEGER;
BEGIN
    -- Serializa altas y cambios de multimedia de la misma mascota.
    -- Sin este bloqueo dos transacciones simultáneas podrían superar el límite.
    PERFORM 1
    FROM mascotas
    WHERE id = NEW.mascota_id
    FOR UPDATE;

    IF NEW.tipo = 'foto' THEN
        SELECT COUNT(*)
        INTO cantidad
        FROM fotos_mascota
        WHERE mascota_id = NEW.mascota_id
          AND tipo = 'foto'
          AND id IS DISTINCT FROM NEW.id;

        IF cantidad >= 4 THEN
            RAISE EXCEPTION
                'Una mascota no puede tener más de 4 fotos';
        END IF;

    ELSIF NEW.tipo = 'video' THEN
        SELECT COUNT(*)
        INTO cantidad
        FROM fotos_mascota
        WHERE mascota_id = NEW.mascota_id
          AND tipo = 'video'
          AND id IS DISTINCT FROM NEW.id;

        IF cantidad >= 1 THEN
            RAISE EXCEPTION
                'Una mascota no puede tener más de 1 video';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_multimedia
BEFORE INSERT OR UPDATE OF mascota_id, tipo ON fotos_mascota
FOR EACH ROW
EXECUTE FUNCTION validar_limite_multimedia();


-- ============================================
-- 4. Trigger: gestionar foto principal
-- ============================================

CREATE OR REPLACE FUNCTION gestionar_foto_principal()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.es_principal = TRUE THEN
        UPDATE fotos_mascota
        SET es_principal = FALSE
        WHERE mascota_id = NEW.mascota_id
          AND id <> NEW.id
          AND tipo = 'foto'
          AND es_principal = TRUE;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_foto_principal
BEFORE INSERT OR UPDATE ON fotos_mascota
FOR EACH ROW
EXECUTE FUNCTION gestionar_foto_principal();

-- Una publicación disponible debe conservar, en todo momento, al menos
-- una foto y una foto principal, incluso después de editar o borrar archivos.
CREATE OR REPLACE FUNCTION validar_multimedia_mascota_publicada()
RETURNS TRIGGER AS $$
DECLARE
    mascota_a_validar BIGINT;
    estado_mascota VARCHAR(20);
    cantidad_fotos INTEGER;
    cantidad_principales INTEGER;
BEGIN
    mascota_a_validar := OLD.mascota_id;

    SELECT estado INTO estado_mascota
    FROM mascotas
    WHERE id = mascota_a_validar;

    IF estado_mascota = 'disponible' THEN
        SELECT COUNT(*) INTO cantidad_fotos
        FROM fotos_mascota
        WHERE mascota_id = mascota_a_validar
          AND tipo = 'foto';

        SELECT COUNT(*) INTO cantidad_principales
        FROM fotos_mascota
        WHERE mascota_id = mascota_a_validar
          AND tipo = 'foto'
          AND es_principal = TRUE;

        IF cantidad_fotos = 0 OR cantidad_principales = 0 THEN
            RAISE EXCEPTION
                'Una mascota disponible debe conservar al menos una foto principal';
        END IF;
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trigger_validar_multimedia_publicada
AFTER DELETE OR UPDATE ON fotos_mascota
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validar_multimedia_mascota_publicada();


-- ============================================
-- 5. Validar fotos antes de publicar mascota
-- ============================================

CREATE OR REPLACE FUNCTION validar_minimo_fotos()
RETURNS TRIGGER AS $$
DECLARE
    cantidad_fotos INTEGER;
    cantidad_principales INTEGER;
BEGIN
    IF NEW.estado = 'disponible' THEN
        SELECT COUNT(*)
        INTO cantidad_fotos
        FROM fotos_mascota
        WHERE mascota_id = NEW.id
          AND tipo = 'foto';

        SELECT COUNT(*)
        INTO cantidad_principales
        FROM fotos_mascota
        WHERE mascota_id = NEW.id
          AND tipo = 'foto'
          AND es_principal = TRUE;

        IF cantidad_fotos = 0 THEN
            RAISE EXCEPTION
                'La mascota necesita al menos una foto para poder publicarse';
        END IF;

        IF cantidad_principales = 0 THEN
            RAISE EXCEPTION
                'La mascota necesita una foto principal para poder publicarse';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_minimo_fotos
BEFORE INSERT OR UPDATE ON mascotas
FOR EACH ROW
EXECUTE FUNCTION validar_minimo_fotos();


-- ============================================
-- VISTA: MASCOTAS CON RANGO DE EDAD (PARA FILTRO)
-- ============================================

CREATE OR REPLACE VIEW mascotas_con_rango AS
SELECT *,
    CASE 
        WHEN edad <= 1 THEN 'cria'
        WHEN edad <= 3 THEN 'joven'
        WHEN edad <= 7 THEN 'adulto'
        ELSE 'senior'
    END AS rango_edad
FROM mascotas;


-- ============================================
-- MÓDULO 2 — GESTIÓN DE ADOPCIONES (PARTE 2)
-- Tabla: solicitudes_adopcion
-- ============================================

CREATE TABLE solicitudes_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT preserva el historial de solicitudes y su solicitante.
    solicitante_id BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    mascota_id BIGINT NOT NULL
        REFERENCES mascotas(id)
        ON DELETE RESTRICT,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',

    -- Información proporcionada por el ciudadano en el formulario
    tiene_otras_mascotas BOOLEAN NOT NULL,
    viven_otras_personas BOOLEAN NOT NULL,
    tiene_espacio_adecuado BOOLEAN NOT NULL,
    zona_aproximada VARCHAR(100) NOT NULL,
    horario_preferido VARCHAR(150) NOT NULL,
    comentarios_solicitante TEXT,
    declara_informacion_veraz BOOLEAN NOT NULL,

    -- Información interna del administrador
    comentarios_admin TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT solicitudes_estado_valido
        CHECK (estado IN (
            'pendiente',
            'en_espera',
            'aceptada',
            'rechazada',
            'cancelada',
            'cerrada'
        )),

    CONSTRAINT solicitud_declaracion_veraz_valida
        CHECK (declara_informacion_veraz = TRUE),

    -- CORRECCIÓN: evita zona/horario en blanco
    CONSTRAINT solicitudes_zona_no_vacia
        CHECK (btrim(zona_aproximada) <> ''),
    CONSTRAINT solicitudes_horario_no_vacio
        CHECK (btrim(horario_preferido) <> '')
);

CREATE INDEX idx_solicitudes_solicitante
ON solicitudes_adopcion(solicitante_id);

CREATE INDEX idx_solicitudes_mascota
ON solicitudes_adopcion(mascota_id);

CREATE INDEX idx_solicitudes_estado
ON solicitudes_adopcion(estado);

CREATE TRIGGER trigger_solicitudes_updated_at
BEFORE UPDATE ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();

-- Un ciudadano solo puede tener una solicitud activa (pendiente o en espera)
-- para la misma mascota.
CREATE UNIQUE INDEX idx_una_solicitud_pendiente
ON solicitudes_adopcion(solicitante_id, mascota_id)
WHERE estado IN ('pendiente', 'en_espera');

-- Una mascota solo puede tener una solicitud aceptada.
CREATE UNIQUE INDEX idx_una_solicitud_aceptada_por_mascota
ON solicitudes_adopcion(mascota_id)
WHERE estado = 'aceptada';

-- Solo se permiten solicitudes para mascotas disponibles.
CREATE OR REPLACE FUNCTION validar_mascota_disponible()
RETURNS TRIGGER AS $$
DECLARE
    estado_mascota VARCHAR(20);
BEGIN
    -- Bloquea la mascota durante la validación. Así una aceptación concurrente
    -- no puede dejar una solicitud pendiente para una mascota ya adoptada.
    SELECT estado
    INTO estado_mascota
    FROM mascotas
    WHERE id = NEW.mascota_id
    FOR UPDATE;

    IF estado_mascota IS NULL THEN
        RAISE EXCEPTION 'La mascota indicada no existe';
    END IF;

    IF estado_mascota <> 'disponible' THEN
        RAISE EXCEPTION 'Esta mascota ya no está disponible para adopción';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_mascota_disponible
BEFORE INSERT OR UPDATE OF mascota_id ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_mascota_disponible();

-- CORRECCIÓN: solo un ciudadano con cuenta activa puede solicitar una adopción.
CREATE OR REPLACE FUNCTION validar_solicitante_valido()
RETURNS TRIGGER AS $$
DECLARE
    rol_usuario VARCHAR(20);
    activo_usuario BOOLEAN;
BEGIN
    SELECT rol, estado INTO rol_usuario, activo_usuario
    FROM usuarios
    WHERE id = NEW.solicitante_id;

    IF rol_usuario IS DISTINCT FROM 'ciudadano' THEN
        RAISE EXCEPTION 'Solo un usuario con rol ciudadano puede solicitar una adopción';
    END IF;

    IF activo_usuario IS DISTINCT FROM TRUE THEN
        RAISE EXCEPTION 'El solicitante debe tener una cuenta activa';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_solicitante_valido
BEFORE INSERT OR UPDATE OF solicitante_id ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_solicitante_valido();

-- CORRECCIÓN DE INTEGRIDAD:
-- Toda solicitud nueva debe nacer en estado 'pendiente'.
-- La aceptación solo puede ocurrir mediante una transición posterior.
CREATE OR REPLACE FUNCTION validar_nueva_solicitud_pendiente()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado <> 'pendiente' THEN
        RAISE EXCEPTION
            'Una nueva solicitud de adopción debe crearse en estado pendiente';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_nueva_solicitud_pendiente
BEFORE INSERT ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_nueva_solicitud_pendiente();

-- Una solicitud representa a una persona y una mascota concretas. Para
-- cambiar cualquiera de ambas se debe registrar una nueva solicitud.
CREATE OR REPLACE FUNCTION validar_datos_inmutables_solicitud()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.mascota_id IS DISTINCT FROM OLD.mascota_id
       OR NEW.solicitante_id IS DISTINCT FROM OLD.solicitante_id THEN
        RAISE EXCEPTION
            'No se puede cambiar la mascota ni el solicitante de una solicitud existente';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_datos_inmutables_solicitud
BEFORE UPDATE OF mascota_id, solicitante_id ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_datos_inmutables_solicitud();

-- Control de cambios de estado.
-- El backend autoriza quién puede cancelar; la base garantiza el flujo:
-- pendiente -> en_espera/aceptada/rechazada/cancelada
-- en_espera -> pendiente/aceptada/rechazada/cancelada
-- cerrada se usa exclusivamente al aceptar otra solicitud para la misma mascota.
CREATE OR REPLACE FUNCTION validar_cambio_estado_solicitud()
RETURNS TRIGGER AS $$
DECLARE
    estado_mascota VARCHAR(20);
BEGIN
    IF OLD.estado IN ('aceptada', 'rechazada', 'cancelada', 'cerrada')
       AND NEW.estado <> OLD.estado THEN
        RAISE EXCEPTION
            'Una solicitud con estado final no puede cambiar de estado';
    END IF;

    -- El cierre se permite solo durante el UPDATE anidado que ejecuta
    -- procesar_aceptacion_solicitud. Una actualización directa entra a este
    -- trigger con profundidad 1; el UPDATE interno del trigger de aceptación,
    -- con profundidad mayor que 1.
    IF NEW.estado = 'cerrada'
       AND OLD.estado <> 'cerrada'
       AND pg_trigger_depth() = 1 THEN
        RAISE EXCEPTION
            'El estado cerrada solo puede asignarse automáticamente al aceptar otra solicitud';
    END IF;

    IF NEW.estado = 'aceptada'
       AND OLD.estado NOT IN ('pendiente', 'en_espera') THEN
        RAISE EXCEPTION
            'Solo se puede aceptar una solicitud pendiente o en espera';
    END IF;

    IF NEW.estado = 'aceptada' AND OLD.estado <> 'aceptada' THEN
        -- Bloquea la mascota durante la decisión para evitar dos aceptaciones
        -- concurrentes o aceptar una mascota que ya dejó de estar disponible.
        SELECT estado INTO estado_mascota
        FROM mascotas
        WHERE id = NEW.mascota_id
        FOR UPDATE;

        IF estado_mascota IS DISTINCT FROM 'disponible' THEN
            RAISE EXCEPTION
                'Solo se puede aceptar una solicitud de una mascota disponible';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_cambio_estado_solicitud
BEFORE UPDATE OF estado ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_cambio_estado_solicitud();

-- ============================================
-- MÓDULO 3 — SEGUIMIENTO POST-ADOPCIÓN
-- Tablas: 1) seguimientos_adopcion
--         2) visitas_seguimiento
--         3) incidencias
-- ============================================

-- ============================================
-- 1. Tabla seguimientos_adopcion
-- ============================================

CREATE TABLE seguimientos_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT: una adopción aceptada no pierde su seguimiento histórico.
    solicitud_id BIGINT NOT NULL UNIQUE
        REFERENCES solicitudes_adopcion(id)
        ON DELETE RESTRICT,

    voluntario_id BIGINT
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    estado VARCHAR(20) NOT NULL DEFAULT 'sin_asignar',

    zona_aproximada VARCHAR(100) NOT NULL,
    horario_preferido VARCHAR(150) NOT NULL,

    fecha_inicio TIMESTAMPTZ,
    fecha_cierre TIMESTAMPTZ,
    observaciones_cierre TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT seguimientos_estado_valido
        CHECK (estado IN ('sin_asignar', 'activo', 'cerrado')),

    CONSTRAINT seguimientos_asignacion_valida
        CHECK (
            (estado = 'sin_asignar'
             AND voluntario_id IS NULL
             AND fecha_inicio IS NULL
             AND fecha_cierre IS NULL)
            OR
            (estado = 'activo'
             AND voluntario_id IS NOT NULL
             AND fecha_inicio IS NOT NULL
             AND fecha_cierre IS NULL)
            OR
            (estado = 'cerrado'
             AND voluntario_id IS NOT NULL
             AND fecha_inicio IS NOT NULL
             AND fecha_cierre IS NOT NULL)
        ),

    CONSTRAINT seguimientos_fechas_validas
        CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_inicio),

    -- CORRECCIÓN: evita zona/horario en blanco
    CONSTRAINT seguimientos_zona_no_vacia
        CHECK (btrim(zona_aproximada) <> ''),
    CONSTRAINT seguimientos_horario_no_vacio
        CHECK (btrim(horario_preferido) <> '')
);

CREATE INDEX idx_seguimientos_estado ON seguimientos_adopcion(estado);
CREATE INDEX idx_seguimientos_voluntario ON seguimientos_adopcion(voluntario_id);

CREATE TRIGGER trigger_seguimientos_updated_at
BEFORE UPDATE ON seguimientos_adopcion
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();

-- CORRECCIÓN DE INTEGRIDAD:
-- Un seguimiento solo puede existir para una solicitud que ya fue aceptada.
CREATE OR REPLACE FUNCTION validar_solicitud_aceptada_para_seguimiento()
RETURNS TRIGGER AS $$
DECLARE
    estado_solicitud VARCHAR(20);
BEGIN
    SELECT estado
    INTO estado_solicitud
    FROM solicitudes_adopcion
    WHERE id = NEW.solicitud_id;

    IF estado_solicitud IS DISTINCT FROM 'aceptada' THEN
        RAISE EXCEPTION
            'Solo se puede crear un seguimiento para una solicitud aceptada';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_solicitud_aceptada_para_seguimiento
BEFORE INSERT OR UPDATE OF solicitud_id
ON seguimientos_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_solicitud_aceptada_para_seguimiento();

CREATE OR REPLACE FUNCTION validar_rol_voluntario()
RETURNS TRIGGER AS $$
DECLARE
    rol_usuario VARCHAR(20);
BEGIN
    IF NEW.voluntario_id IS NOT NULL THEN
        SELECT rol INTO rol_usuario
        FROM usuarios
        WHERE id = NEW.voluntario_id;

        IF rol_usuario IS DISTINCT FROM 'voluntario' THEN
            RAISE EXCEPTION 'El usuario asignado debe tener el rol de voluntario';
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM usuarios
            WHERE id = NEW.voluntario_id
              AND estado = TRUE
        ) THEN
            RAISE EXCEPTION 'El voluntario asignado debe tener una cuenta activa';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_rol_voluntario_seguimiento
BEFORE INSERT OR UPDATE OF voluntario_id ON seguimientos_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_rol_voluntario();


-- ============================================
-- 2. Tabla visitas_seguimiento
-- ============================================

CREATE TABLE visitas_seguimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT preserva el historial de visitas e incidencias.
    seguimiento_id BIGINT NOT NULL
        REFERENCES seguimientos_adopcion(id)
        ON DELETE RESTRICT,

    voluntario_id BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    fecha_programada DATE NOT NULL,
    fecha_realizada TIMESTAMPTZ,

    observaciones TEXT,
    estado_salud VARCHAR(50),
    foto_url VARCHAR(255),

    estado VARCHAR(20) NOT NULL DEFAULT 'programada',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT visitas_estado_valido
        CHECK (estado IN ('programada', 'realizada', 'no_asistio')),

    CONSTRAINT visitas_fecha_realizada_valida
        CHECK (
            (estado = 'realizada' AND fecha_realizada IS NOT NULL)
            OR
            (estado IN ('programada', 'no_asistio') AND fecha_realizada IS NULL)
        ),

    -- CORRECCIÓN: una visita no puede realizarse antes de su fecha programada
    CONSTRAINT visitas_cronologia_valida
        CHECK (fecha_realizada IS NULL OR fecha_realizada::date >= fecha_programada),

    -- SEGURIDAD / INTEGRIDAD: una foto opcional, si se informa, debe tener URL.
    CONSTRAINT visitas_foto_url_no_vacia
        CHECK (foto_url IS NULL OR btrim(foto_url) <> '')
);

CREATE INDEX idx_visitas_seguimiento ON visitas_seguimiento(seguimiento_id);
CREATE INDEX idx_visitas_voluntario ON visitas_seguimiento(voluntario_id);

CREATE TRIGGER trigger_visitas_updated_at
BEFORE UPDATE ON visitas_seguimiento
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();

CREATE OR REPLACE FUNCTION validar_visita_seguimiento()
RETURNS TRIGGER AS $$
DECLARE
    voluntario_asignado BIGINT;
    estado_seguimiento VARCHAR(20);
BEGIN
    SELECT voluntario_id, estado
    INTO voluntario_asignado, estado_seguimiento
    FROM seguimientos_adopcion
    WHERE id = NEW.seguimiento_id
    FOR UPDATE;

    IF estado_seguimiento IS DISTINCT FROM 'activo' THEN
        RAISE EXCEPTION 'Solo se pueden registrar visitas en seguimientos activos';
    END IF;

    IF voluntario_asignado IS DISTINCT FROM NEW.voluntario_id THEN
        RAISE EXCEPTION 'La visita debe registrarla el voluntario asignado al caso';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- CORRECCIÓN: se acota a INSERT y a cambios de seguimiento_id/voluntario_id.
-- Sin esta acotación, cualquier edición de la visita (observaciones,
-- estado_salud, fecha_realizada, estado) revalidaba innecesariamente que el
-- seguimiento siguiera 'activo' y que el voluntario asignado coincidiera,
-- bloqueando correcciones legítimas después del alta o del cierre del caso.
CREATE TRIGGER trigger_validar_visita_seguimiento
BEFORE INSERT OR UPDATE OF seguimiento_id, voluntario_id ON visitas_seguimiento
FOR EACH ROW
EXECUTE FUNCTION validar_visita_seguimiento();

CREATE OR REPLACE FUNCTION validar_limite_visitas()
RETURNS TRIGGER AS $$
DECLARE
    cantidad INTEGER;
BEGIN
    -- Serializa el conteo de visitas del mismo caso.
    PERFORM 1
    FROM seguimientos_adopcion
    WHERE id = NEW.seguimiento_id
    FOR UPDATE;

    SELECT COUNT(*) INTO cantidad
    FROM visitas_seguimiento
    WHERE seguimiento_id = NEW.seguimiento_id
      AND id IS DISTINCT FROM NEW.id;

    IF cantidad >= 2 THEN
        RAISE EXCEPTION 'Una adopción no puede tener más de 2 visitas de seguimiento';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_limite_visitas
BEFORE INSERT OR UPDATE OF seguimiento_id ON visitas_seguimiento
FOR EACH ROW
EXECUTE FUNCTION validar_limite_visitas();


-- ============================================
-- 3. Tabla incidencias
-- ============================================

CREATE TABLE incidencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seguimiento_id BIGINT NOT NULL
        REFERENCES seguimientos_adopcion(id)
        ON DELETE RESTRICT,

    visita_id BIGINT
        REFERENCES visitas_seguimiento(id)
        ON DELETE RESTRICT,

    reportado_por BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    tipo VARCHAR(30) NOT NULL,
    descripcion TEXT NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    comentarios_resolucion TEXT,
    atendida_por BIGINT
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,
    atendida_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT incidencias_tipo_valido
        CHECK (tipo IN ('salud', 'maltrato', 'perdida_contacto', 'otro')),

    CONSTRAINT incidencias_estado_valido
        CHECK (estado IN ('pendiente', 'en_proceso', 'atendida')),

    CONSTRAINT incidencias_resolucion_valida
        CHECK (
            (estado = 'atendida'
             AND comentarios_resolucion IS NOT NULL
             AND atendida_por IS NOT NULL
             AND atendida_at IS NOT NULL)
            OR
            (estado IN ('pendiente', 'en_proceso')
             AND atendida_por IS NULL
             AND atendida_at IS NULL)
        ),

    CONSTRAINT incidencias_fecha_atencion_valida
        CHECK (atendida_at IS NULL OR atendida_at >= created_at),

    -- CORRECCIÓN: evita descripción/comentario de resolución en blanco
    CONSTRAINT incidencias_descripcion_no_vacia
        CHECK (btrim(descripcion) <> ''),
    CONSTRAINT incidencias_comentarios_resolucion_no_vacio
        CHECK (comentarios_resolucion IS NULL OR btrim(comentarios_resolucion) <> '')
);

CREATE INDEX idx_incidencias_seguimiento ON incidencias(seguimiento_id);
CREATE INDEX idx_incidencias_visita ON incidencias(visita_id);
CREATE INDEX idx_incidencias_estado ON incidencias(estado);
CREATE INDEX idx_incidencias_reportado_por ON incidencias(reportado_por);
CREATE INDEX idx_incidencias_atendida_por ON incidencias(atendida_por);

CREATE TRIGGER trigger_incidencias_updated_at
BEFORE UPDATE ON incidencias
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();

CREATE OR REPLACE FUNCTION validar_visita_del_mismo_seguimiento()
RETURNS TRIGGER AS $$
DECLARE
    seguimiento_de_la_visita BIGINT;
BEGIN
    IF NEW.visita_id IS NOT NULL THEN
        SELECT seguimiento_id INTO seguimiento_de_la_visita
        FROM visitas_seguimiento
        WHERE id = NEW.visita_id;

        IF seguimiento_de_la_visita IS DISTINCT FROM NEW.seguimiento_id THEN
            RAISE EXCEPTION 'La visita indicada no pertenece a este caso de seguimiento';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_visita_del_mismo_seguimiento
BEFORE INSERT OR UPDATE OF seguimiento_id, visita_id ON incidencias
FOR EACH ROW
EXECUTE FUNCTION validar_visita_del_mismo_seguimiento();

CREATE OR REPLACE FUNCTION validar_reportante_incidencia()
RETURNS TRIGGER AS $$
DECLARE
    voluntario_asignado BIGINT;
    estado_seguimiento VARCHAR(20);
BEGIN
    SELECT voluntario_id, estado
    INTO voluntario_asignado, estado_seguimiento
    FROM seguimientos_adopcion
    WHERE id = NEW.seguimiento_id;

    IF estado_seguimiento IS DISTINCT FROM 'activo' THEN
        RAISE EXCEPTION 'Solo se pueden registrar incidencias en seguimientos activos';
    END IF;

    IF voluntario_asignado IS DISTINCT FROM NEW.reportado_por THEN
        RAISE EXCEPTION 'La incidencia debe reportarla el voluntario asignado al caso';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- CORRECCIÓN: se acota a INSERT y a cambios de seguimiento_id/reportado_por.
-- Antes se disparaba en cualquier UPDATE de la fila, así que en cuanto el
-- seguimiento pasaba a 'cerrado' quedaba bloqueada incluso una simple
-- corrección de texto en una incidencia ya existente.
CREATE TRIGGER trigger_validar_reportante_incidencia
BEFORE INSERT OR UPDATE OF seguimiento_id, reportado_por ON incidencias
FOR EACH ROW
EXECUTE FUNCTION validar_reportante_incidencia();

CREATE OR REPLACE FUNCTION validar_cambio_estado_incidencia()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.estado = 'atendida'
       AND NEW.estado <> 'atendida' THEN
        RAISE EXCEPTION 'Una incidencia atendida no puede volver a abrirse';
    END IF;

    IF NEW.estado = 'atendida' AND OLD.estado <> 'atendida' THEN
        IF NEW.comentarios_resolucion IS NULL
           OR NEW.atendida_por IS NULL
           OR NEW.atendida_at IS NULL THEN
            RAISE EXCEPTION
                'Para atender una incidencia se requiere comentario, responsable y fecha de atención';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_cambio_estado_incidencia
BEFORE UPDATE OF estado ON incidencias
FOR EACH ROW
EXECUTE FUNCTION validar_cambio_estado_incidencia();

-- CORRECCIÓN: solo el administrador o el voluntario asignado al caso
-- (y con cuenta activa) pueden quedar registrados como quien atendió.
CREATE OR REPLACE FUNCTION validar_atendida_por_incidencia()
RETURNS TRIGGER AS $$
DECLARE
    rol_usuario VARCHAR(20);
    activo_usuario BOOLEAN;
    voluntario_asignado BIGINT;
BEGIN
    IF NEW.atendida_por IS NOT NULL THEN
        SELECT rol, estado INTO rol_usuario, activo_usuario
        FROM usuarios
        WHERE id = NEW.atendida_por;

        IF activo_usuario IS DISTINCT FROM TRUE THEN
            RAISE EXCEPTION 'Quien atiende la incidencia debe tener una cuenta activa';
        END IF;

        IF rol_usuario = 'administrador' THEN
            -- permitido
        ELSIF rol_usuario = 'voluntario' THEN
            SELECT voluntario_id INTO voluntario_asignado
            FROM seguimientos_adopcion
            WHERE id = NEW.seguimiento_id;

            IF voluntario_asignado IS DISTINCT FROM NEW.atendida_por THEN
                RAISE EXCEPTION 'Solo el administrador o el voluntario asignado al caso pueden atender la incidencia';
            END IF;
        ELSE
            RAISE EXCEPTION 'Solo el administrador o el voluntario asignado al caso pueden atender la incidencia';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_atendida_por_incidencia
BEFORE INSERT OR UPDATE OF seguimiento_id, atendida_por ON incidencias
FOR EACH ROW
EXECUTE FUNCTION validar_atendida_por_incidencia();

-- ============================================
-- VALIDACIÓN DE CIERRE DEL SEGUIMIENTO
-- Depende de visitas_seguimiento e incidencias, por eso se define después
-- de crear las tres tablas del Módulo 3.
-- ============================================
CREATE OR REPLACE FUNCTION validar_cierre_seguimiento()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'cerrado' AND OLD.estado <> 'cerrado' THEN
        IF EXISTS (
            SELECT 1 FROM visitas_seguimiento
            WHERE seguimiento_id = NEW.id
              AND estado = 'programada'
        ) THEN
            RAISE EXCEPTION
                'No se puede cerrar un seguimiento con visitas programadas pendientes';
        END IF;

        IF EXISTS (
            SELECT 1 FROM incidencias
            WHERE seguimiento_id = NEW.id
              AND estado <> 'atendida'
        ) THEN
            RAISE EXCEPTION
                'No se puede cerrar un seguimiento con incidencias sin atender';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_cierre_seguimiento
BEFORE UPDATE OF estado ON seguimientos_adopcion
FOR EACH ROW
EXECUTE FUNCTION validar_cierre_seguimiento();

-- ============================================
-- PROTECCIÓN DEL ESTADO DE MASCOTAS
-- ============================================
-- Una mascota solo llega a 'adoptada' desde el trigger interno que procesa
-- la aceptación de una solicitud. pg_trigger_depth() distingue esa escritura
-- encadenada de un UPDATE directo sobre mascotas, y la solicitud aceptada se
-- comprueba además para la misma mascota.
CREATE OR REPLACE FUNCTION proteger_estado_mascota()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' AND NEW.estado = 'adoptada' THEN
        RAISE EXCEPTION
            'Una mascota no puede crearse directamente con estado adoptada';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.estado = 'adoptada' AND NEW.estado <> OLD.estado THEN
            RAISE EXCEPTION
                'Una mascota adoptada no puede cambiar nuevamente de estado';
        END IF;

        IF NEW.estado = 'adoptada' AND OLD.estado <> 'adoptada' THEN
            IF pg_trigger_depth() < 2
               OR NOT EXISTS (
                    SELECT 1
                    FROM solicitudes_adopcion
                    WHERE mascota_id = NEW.id
                      AND estado = 'aceptada'
               ) THEN
                RAISE EXCEPTION
                    'El estado adoptada solo puede establecerse al aceptar una solicitud';
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_proteger_estado_mascota
BEFORE INSERT OR UPDATE OF estado ON mascotas
FOR EACH ROW
EXECUTE FUNCTION proteger_estado_mascota();

-- ============================================
-- DEPENDENCIA CRUZADA: ADOPCIÓN -> SEGUIMIENTO
-- ============================================
-- Al aceptar una solicitud, adopta la mascota, cierra las demás solicitudes
-- activas (pendientes o en espera) y crea el caso de seguimiento.
-- Se define aquí, después de crear seguimientos_adopcion, para mantener
-- el orden natural de dependencias del script.
CREATE OR REPLACE FUNCTION procesar_aceptacion_solicitud()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'aceptada'
       AND OLD.estado <> 'aceptada' THEN

        UPDATE mascotas
        SET estado = 'adoptada'
        WHERE id = NEW.mascota_id;

        UPDATE solicitudes_adopcion
        SET estado = 'cerrada'
        WHERE mascota_id = NEW.mascota_id
          AND id <> NEW.id
          AND estado IN ('pendiente', 'en_espera');

        -- Crea el caso de seguimiento, copiando zona y horario
        -- que el ciudadano indicó en su solicitud.
        INSERT INTO seguimientos_adopcion (solicitud_id, zona_aproximada, horario_preferido)
        VALUES (NEW.id, NEW.zona_aproximada, NEW.horario_preferido);

    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_procesar_aceptacion
AFTER UPDATE OF estado ON solicitudes_adopcion
FOR EACH ROW
EXECUTE FUNCTION procesar_aceptacion_solicitud();


-- ============================================
-- MÓDULO 4 — GESTIÓN DE VOLUNTARIOS
-- Tablas: 1) postulaciones_voluntariado
--         2) voluntarios
-- (Actividad/turno se resuelve con seguimientos_adopcion, ya existente:
--  el voluntario "elige 1 caso" = se le asigna un seguimientos_adopcion.voluntario_id)
-- ============================================

-- ============================================
-- 1. Tabla postulaciones_voluntariado
-- Historial de solicitudes para ser voluntario.
-- ============================================

CREATE TABLE postulaciones_voluntariado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT preserva el historial de postulaciones y revisiones.
    usuario_id BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    motivacion TEXT NOT NULL,
    habilidades TEXT,
    disponibilidad VARCHAR(150) NOT NULL,
    zona_preferencia VARCHAR(100) NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    comentarios_admin TEXT,

    revisado_por BIGINT
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,
    revisado_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT postulaciones_estado_valido
        CHECK (estado IN ('pendiente', 'aprobada', 'rechazada', 'cancelada')),

    -- Aprobada/rechazada exigen quién y cuándo revisó; cancelada la hace
    -- el propio ciudadano y no requiere revisión administrativa.
    CONSTRAINT postulaciones_revision_valida
        CHECK (
            (estado = 'pendiente'
             AND revisado_por IS NULL AND revisado_at IS NULL)
            OR
            (estado IN ('aprobada', 'rechazada')
             AND revisado_por IS NOT NULL AND revisado_at IS NOT NULL)
            OR
            (estado = 'cancelada'
             AND revisado_por IS NULL AND revisado_at IS NULL)
        ),

    CONSTRAINT postulaciones_motivacion_no_vacia CHECK (btrim(motivacion) <> ''),
    CONSTRAINT postulaciones_disponibilidad_no_vacia CHECK (btrim(disponibilidad) <> ''),
    CONSTRAINT postulaciones_zona_no_vacia CHECK (btrim(zona_preferencia) <> '')
);

CREATE INDEX idx_postulaciones_usuario ON postulaciones_voluntariado(usuario_id);
CREATE INDEX idx_postulaciones_estado ON postulaciones_voluntariado(estado);
CREATE INDEX idx_postulaciones_revisado_por ON postulaciones_voluntariado(revisado_por);

-- Un mismo usuario no puede tener dos postulaciones pendientes a la vez.
CREATE UNIQUE INDEX idx_una_postulacion_pendiente
    ON postulaciones_voluntariado(usuario_id)
    WHERE estado = 'pendiente';

-- Clave candidata para garantizar que una postulación y su usuario
-- pertenezcan a la misma persona cuando se cree el perfil de voluntario.
ALTER TABLE postulaciones_voluntariado
    ADD CONSTRAINT postulacion_id_usuario_unico
    UNIQUE (id, usuario_id);

CREATE TRIGGER trigger_postulaciones_updated_at
BEFORE UPDATE ON postulaciones_voluntariado
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();

-- Las decisiones administrativas solo pueden ser registradas por un
-- administrador con cuenta activa. También evita conservar revisión en una
-- postulación cancelada.
CREATE OR REPLACE FUNCTION validar_revisor_postulacion()
RETURNS TRIGGER AS $$
DECLARE
    rol_revisor VARCHAR(20);
    activo_revisor BOOLEAN;
BEGIN
    IF NEW.estado IN ('aprobada', 'rechazada') THEN
        SELECT rol, estado INTO rol_revisor, activo_revisor
        FROM usuarios
        WHERE id = NEW.revisado_por;

        IF rol_revisor IS DISTINCT FROM 'administrador'
           OR activo_revisor IS DISTINCT FROM TRUE THEN
            RAISE EXCEPTION
                'La postulación debe revisarla un administrador con cuenta activa';
        END IF;
    END IF;

    IF NEW.estado = 'cancelada'
       AND (NEW.revisado_por IS NOT NULL OR NEW.revisado_at IS NOT NULL) THEN
        RAISE EXCEPTION
            'Una postulación cancelada no puede conservar datos de revisión';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_revisor_postulacion
BEFORE INSERT OR UPDATE OF estado, revisado_por, revisado_at
ON postulaciones_voluntariado
FOR EACH ROW
EXECUTE FUNCTION validar_revisor_postulacion();

-- Una vez que la postulación sale de 'pendiente', queda fija
-- (misma lógica de estados cerrados usada en solicitudes_adopcion).
CREATE OR REPLACE FUNCTION validar_cambio_estado_postulacion()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.estado <> 'pendiente' AND NEW.estado <> OLD.estado THEN
        RAISE EXCEPTION
            'Solo se puede cambiar el estado de una postulación pendiente';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_cambio_estado_postulacion
BEFORE UPDATE OF estado ON postulaciones_voluntariado
FOR EACH ROW
EXECUTE FUNCTION validar_cambio_estado_postulacion();

-- ============================================
-- 2. Tabla voluntarios
-- Perfil aprobado. Una sola fila por usuario (usuario_id UNIQUE);
-- "dar de baja" desactiva la fila, no la elimina.
-- ============================================

CREATE TABLE voluntarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usuario_id BIGINT NOT NULL UNIQUE
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    postulacion_id BIGINT NOT NULL UNIQUE,

    habilidades TEXT,
    disponibilidad VARCHAR(150) NOT NULL,
    zona_preferencia VARCHAR(100) NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'activo',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT voluntarios_estado_valido
        CHECK (estado IN ('activo', 'inactivo')),

    CONSTRAINT voluntarios_disponibilidad_no_vacia CHECK (btrim(disponibilidad) <> ''),
    CONSTRAINT voluntarios_zona_no_vacia CHECK (btrim(zona_preferencia) <> '')
);

CREATE INDEX idx_voluntarios_estado ON voluntarios(estado);

-- CORRECCIÓN DE INTEGRIDAD:
-- El perfil de voluntario debe apuntar a una postulación del mismo usuario.
ALTER TABLE voluntarios
    ADD CONSTRAINT fk_voluntario_postulacion_mismo_usuario
    FOREIGN KEY (postulacion_id, usuario_id)
    REFERENCES postulaciones_voluntariado(id, usuario_id)
    ON DELETE RESTRICT;

-- La FK compuesta valida que postulación y usuario sean de la misma persona.
-- Este trigger completa la regla: el perfil solo existe desde una postulación
-- aprobada y para una cuenta activa cuyo rol ya fue promovido a voluntario.
CREATE OR REPLACE FUNCTION validar_voluntario_desde_postulacion()
RETURNS TRIGGER AS $$
DECLARE
    estado_postulacion VARCHAR(20);
    usuario_postulacion BIGINT;
    rol_usuario VARCHAR(20);
    activo_usuario BOOLEAN;
BEGIN
    SELECT p.estado, p.usuario_id, u.rol, u.estado
    INTO estado_postulacion, usuario_postulacion, rol_usuario, activo_usuario
    FROM postulaciones_voluntariado p
    JOIN usuarios u ON u.id = NEW.usuario_id
    WHERE p.id = NEW.postulacion_id;

    IF estado_postulacion IS NULL THEN
        RAISE EXCEPTION 'La postulación indicada no existe';
    END IF;

    IF usuario_postulacion IS DISTINCT FROM NEW.usuario_id THEN
        RAISE EXCEPTION
            'La postulación indicada no corresponde al usuario del voluntario';
    END IF;

    IF estado_postulacion <> 'aprobada' THEN
        RAISE EXCEPTION
            'Solo una postulación aprobada puede generar un perfil de voluntario';
    END IF;

    IF rol_usuario IS DISTINCT FROM 'voluntario'
       OR activo_usuario IS DISTINCT FROM TRUE THEN
        RAISE EXCEPTION
            'El perfil requiere un usuario voluntario con cuenta activa';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_voluntario_desde_postulacion
BEFORE INSERT OR UPDATE OF usuario_id, postulacion_id ON voluntarios
FOR EACH ROW
EXECUTE FUNCTION validar_voluntario_desde_postulacion();

CREATE TRIGGER trigger_voluntarios_updated_at
BEFORE UPDATE ON voluntarios
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();


-- Solo un ciudadano activo puede postularse, y no si ya tiene
-- un perfil de voluntario activo.
CREATE OR REPLACE FUNCTION validar_postulante_valido()
RETURNS TRIGGER AS $$
DECLARE
    rol_usuario VARCHAR(20);
    activo_usuario BOOLEAN;
BEGIN
    SELECT rol, estado INTO rol_usuario, activo_usuario
    FROM usuarios
    WHERE id = NEW.usuario_id;

    IF rol_usuario IS DISTINCT FROM 'ciudadano' THEN
        RAISE EXCEPTION 'Solo un usuario con rol ciudadano puede postularse como voluntario';
    END IF;

    IF activo_usuario IS DISTINCT FROM TRUE THEN
        RAISE EXCEPTION 'El postulante debe tener una cuenta activa';
    END IF;

    IF EXISTS (
        SELECT 1 FROM voluntarios
        WHERE usuario_id = NEW.usuario_id
          AND estado = 'activo'
    ) THEN
        RAISE EXCEPTION 'El usuario ya tiene un perfil de voluntario activo';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_validar_postulante_valido
BEFORE INSERT OR UPDATE OF usuario_id ON postulaciones_voluntariado
FOR EACH ROW
EXECUTE FUNCTION validar_postulante_valido();


-- Al aprobar: sube el rol del usuario a 'voluntario' y crea (o reactiva)
-- su perfil en la tabla voluntarios.
CREATE OR REPLACE FUNCTION procesar_aprobacion_postulacion()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'aprobada' AND OLD.estado <> 'aprobada' THEN

        UPDATE usuarios
        SET rol = 'voluntario'
        WHERE id = NEW.usuario_id;

        IF EXISTS (SELECT 1 FROM voluntarios WHERE usuario_id = NEW.usuario_id) THEN
            UPDATE voluntarios
            SET estado = 'activo',
                postulacion_id = NEW.id,
                habilidades = NEW.habilidades,
                disponibilidad = NEW.disponibilidad,
                zona_preferencia = NEW.zona_preferencia,
                updated_at = CURRENT_TIMESTAMP
            WHERE usuario_id = NEW.usuario_id;
        ELSE
            INSERT INTO voluntarios (usuario_id, postulacion_id, habilidades, disponibilidad, zona_preferencia)
            VALUES (NEW.usuario_id, NEW.id, NEW.habilidades, NEW.disponibilidad, NEW.zona_preferencia);
        END IF;

    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_procesar_aprobacion_postulacion
AFTER UPDATE OF estado ON postulaciones_voluntariado
FOR EACH ROW
EXECUTE FUNCTION procesar_aprobacion_postulacion();


-- Evita dejar casos activos asignados a cuentas inactivas o sin rol de voluntario.
CREATE OR REPLACE FUNCTION proteger_voluntario_asignado()
RETURNS TRIGGER AS $$
BEGIN
    -- La baja normal primero cambia voluntarios.estado a 'inactivo' y luego
    -- este trigger permite devolver la cuenta al rol ciudadano.
    IF (NEW.rol <> 'voluntario' OR NEW.estado = FALSE)
       AND EXISTS (
           SELECT 1
           FROM voluntarios
           WHERE usuario_id = OLD.id
             AND estado = 'activo'
       ) THEN
        RAISE EXCEPTION
            'Primero debe darse de baja el perfil activo del voluntario';
    END IF;

    IF (NEW.rol <> 'voluntario' OR NEW.estado = FALSE)
       AND EXISTS (
           SELECT 1
           FROM seguimientos_adopcion
           WHERE voluntario_id = OLD.id
             AND estado = 'activo'
       ) THEN
        RAISE EXCEPTION
            'No se puede cambiar el rol ni desactivar a un voluntario con seguimientos activos';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_proteger_voluntario_asignado
BEFORE UPDATE OF rol, estado ON usuarios
FOR EACH ROW
EXECUTE FUNCTION proteger_voluntario_asignado();

-- Al dar de baja al voluntario, su cuenta vuelve a rol 'ciudadano'.
-- Si tiene seguimientos activos asignados, trigger_proteger_voluntario_asignado
-- (Módulo 3) bloqueará este UPDATE en cascada, evitando dejar casos huérfanos.
CREATE OR REPLACE FUNCTION procesar_baja_voluntario()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.estado = 'inactivo' AND OLD.estado <> 'inactivo' THEN
        UPDATE usuarios
        SET rol = 'ciudadano'
        WHERE id = NEW.usuario_id
          AND rol = 'voluntario';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_procesar_baja_voluntario
AFTER UPDATE OF estado ON voluntarios
FOR EACH ROW
EXECUTE FUNCTION procesar_baja_voluntario();


-- ============================================
-- MÓDULO 5 — REPORTES
-- Tablas: ninguna (solo vistas de lectura)
-- Sin CRUD propio (solo lectura). Se implementa 100% con vistas
-- que consultan los módulos 1-4, sin tablas ni triggers nuevos.
-- ============================================

-- ============================================
-- 1. Vista: resumen general (KPIs para el dashboard del admin)
-- Devuelve una sola fila con los indicadores clave del sistema.
-- ============================================

CREATE OR REPLACE VIEW vista_resumen_general AS
SELECT
    (SELECT COUNT(*) FROM mascotas WHERE estado = 'disponible')
        AS mascotas_disponibles,
    (SELECT COUNT(*) FROM mascotas WHERE estado = 'adoptada')
        AS mascotas_adoptadas_total,
    (SELECT COUNT(*) FROM solicitudes_adopcion
        WHERE estado = 'aceptada'
          AND updated_at >= date_trunc('month', CURRENT_DATE))
        AS adopciones_este_mes,
    (SELECT COUNT(*) FROM solicitudes_adopcion WHERE estado = 'pendiente')
        AS solicitudes_pendientes,
    (SELECT COUNT(*) FROM seguimientos_adopcion WHERE estado = 'activo')
        AS seguimientos_activos,
    (SELECT COUNT(*) FROM seguimientos_adopcion WHERE estado = 'sin_asignar')
        AS seguimientos_sin_asignar,
    (SELECT COUNT(*) FROM incidencias WHERE estado <> 'atendida')
        AS incidencias_sin_atender,
    (SELECT COUNT(*) FROM voluntarios WHERE estado = 'activo')
        AS voluntarios_activos,
    (SELECT COUNT(*) FROM postulaciones_voluntariado WHERE estado = 'pendiente')
        AS postulaciones_pendientes;


-- ============================================
-- 2. Vista: adopciones realizadas
-- ============================================

CREATE OR REPLACE VIEW vista_adopciones_realizadas AS
SELECT
    s.id                          AS solicitud_id,
    m.id                          AS mascota_id,
    m.nombre                      AS mascota_nombre,
    m.especie,
    u.id                          AS adoptante_id,
    u.nombres || ' ' || u.apellidos AS adoptante_nombre,
    s.updated_at                  AS fecha_adopcion,
    sg.id                         AS seguimiento_id,
    sg.estado                     AS estado_seguimiento,
    sg.voluntario_id
FROM solicitudes_adopcion s
JOIN mascotas m ON m.id = s.mascota_id
JOIN usuarios u ON u.id = s.solicitante_id
LEFT JOIN seguimientos_adopcion sg ON sg.solicitud_id = s.id
WHERE s.estado = 'aceptada';


-- ============================================
-- 3. Vista: catálogo de mascotas disponibles (agrupado, para gráficos)
-- Reutiliza mascotas_con_rango (Módulo 2) para el rango de edad.
-- ============================================

CREATE OR REPLACE VIEW vista_mascotas_disponibles_catalogo AS
SELECT
    especie,
    tamano,
    sexo,
    rango_edad,
    COUNT(*) AS cantidad
FROM mascotas_con_rango
WHERE estado = 'disponible'
GROUP BY especie, tamano, sexo, rango_edad
ORDER BY especie, tamano, sexo, rango_edad;


-- ============================================
-- 4. Vista: seguimientos activos (para el tablero de seguimiento)
-- ============================================

CREATE OR REPLACE VIEW vista_seguimientos_activos AS
SELECT
    sg.id                             AS seguimiento_id,
    m.nombre                          AS mascota_nombre,
    m.especie,
    ua.nombres || ' ' || ua.apellidos AS adoptante_nombre,
    uv.nombres || ' ' || uv.apellidos AS voluntario_nombre,
    sg.fecha_inicio,
    (CURRENT_DATE - sg.fecha_inicio::date) AS dias_transcurridos,
    (SELECT COUNT(*) FROM visitas_seguimiento v
        WHERE v.seguimiento_id = sg.id AND v.estado = 'realizada')
        AS visitas_realizadas,
    (SELECT COUNT(*) FROM incidencias i
        WHERE i.seguimiento_id = sg.id AND i.estado <> 'atendida')
        AS incidencias_pendientes
FROM seguimientos_adopcion sg
JOIN solicitudes_adopcion s ON s.id = sg.solicitud_id
JOIN mascotas m ON m.id = s.mascota_id
JOIN usuarios ua ON ua.id = s.solicitante_id
LEFT JOIN usuarios uv ON uv.id = sg.voluntario_id
WHERE sg.estado = 'activo';


-- ============================================
-- 5. Vista: participación de voluntarios
-- ============================================

CREATE OR REPLACE VIEW vista_participacion_voluntarios AS
SELECT
    u.id                             AS voluntario_id,
    u.nombres || ' ' || u.apellidos  AS voluntario_nombre,
    v.estado                         AS estado_perfil,
    (SELECT COUNT(*) FROM seguimientos_adopcion sg
        WHERE sg.voluntario_id = u.id AND sg.estado = 'activo')
        AS casos_activos,
    (SELECT COUNT(*) FROM seguimientos_adopcion sg
        WHERE sg.voluntario_id = u.id AND sg.estado = 'cerrado')
        AS casos_cerrados,
    (SELECT COUNT(*) FROM visitas_seguimiento vs
        WHERE vs.voluntario_id = u.id AND vs.estado = 'realizada')
        AS visitas_realizadas,
    (SELECT COUNT(*) FROM incidencias i
        WHERE i.atendida_por = u.id)
        AS incidencias_atendidas
FROM usuarios u
JOIN voluntarios v ON v.usuario_id = u.id
ORDER BY casos_activos DESC;


-- ============================================
-- POLÍTICA DE ELIMINACIÓN
-- ============================================
-- fotos_mascota -> mascotas usa ON DELETE CASCADE: los archivos no tienen
-- sentido sin su mascota. Las demás claves foráneas usan ON DELETE RESTRICT:
-- solicitudes, adopciones, seguimientos, visitas, incidencias, postulaciones
-- y perfiles conservan historial y no deben quedar huérfanos ni borrarse en
-- cascada. La baja funcional de usuarios y voluntarios se modela con estado.

-- ============================================
-- PRUEBAS DE INTEGRIDAD RECOMENDADAS (EJECUTAR EN DESARROLLO)
-- ============================================
-- Sustituya los marcadores :... por identificadores de datos de prueba.
-- Envuelva los casos de error en BEGIN/ROLLBACK para no alterar datos reales.
--
-- A. Solicitud para mascota disponible: debe funcionar.
-- INSERT INTO solicitudes_adopcion
--     (solicitante_id, mascota_id, tiene_otras_mascotas, viven_otras_personas,
--      tiene_espacio_adecuado, zona_aproximada, horario_preferido,
--      declara_informacion_veraz)
-- VALUES (:ciudadano_id, :mascota_disponible_id, FALSE, FALSE, TRUE,
--         'Zona de prueba', 'Tardes', TRUE);
--
-- B. Solicitud para mascota adoptada: debe fallar.
-- INSERT INTO solicitudes_adopcion
--     (solicitante_id, mascota_id, tiene_otras_mascotas, viven_otras_personas,
--      tiene_espacio_adecuado, zona_aproximada, horario_preferido,
--      declara_informacion_veraz)
-- VALUES (:ciudadano_id, :mascota_adoptada_id, FALSE, FALSE, TRUE,
--         'Zona de prueba', 'Tardes', TRUE);
--
-- C. Inserción directa con estado aceptada: debe fallar.
-- INSERT INTO solicitudes_adopcion
--     (solicitante_id, mascota_id, estado, tiene_otras_mascotas,
--      viven_otras_personas, tiene_espacio_adecuado, zona_aproximada,
--      horario_preferido, declara_informacion_veraz)
-- VALUES (:ciudadano_id, :mascota_disponible_id, 'aceptada', FALSE, FALSE,
--         TRUE, 'Zona de prueba', 'Tardes', TRUE);
--
-- D. Seguimiento para solicitud pendiente: debe fallar.
-- INSERT INTO seguimientos_adopcion
--     (solicitud_id, zona_aproximada, horario_preferido)
-- VALUES (:solicitud_pendiente_id, 'Zona de prueba', 'Tardes');
--
-- E. Aceptación legítima: debe adoptar la mascota, cerrar las demás
-- solicitudes activas y crear un seguimiento.
-- UPDATE solicitudes_adopcion SET estado = 'aceptada'
-- WHERE id = :solicitud_pendiente_id;
-- SELECT estado FROM mascotas WHERE id = :mascota_disponible_id;
-- SELECT id, estado FROM solicitudes_adopcion WHERE mascota_id = :mascota_disponible_id;
-- SELECT id, estado FROM seguimientos_adopcion WHERE solicitud_id = :solicitud_pendiente_id;
--
-- F. Cambio directo de mascota a adoptada: debe fallar.
-- UPDATE mascotas SET estado = 'adoptada' WHERE id = :otra_mascota_disponible_id;
--
-- G. Voluntario con postulación pendiente: debe fallar.
-- INSERT INTO voluntarios
--     (usuario_id, postulacion_id, disponibilidad, zona_preferencia)
-- VALUES (:ciudadano_id, :postulacion_pendiente_id, 'Fines de semana', 'Zona de prueba');
--
-- H. Voluntario con postulación aprobada y usuario promovido: debe funcionar.
-- INSERT INTO voluntarios
--     (usuario_id, postulacion_id, disponibilidad, zona_preferencia)
-- VALUES (:usuario_voluntario_id, :postulacion_aprobada_id,
--         'Fines de semana', 'Zona de prueba');
--
-- I. Usuario y postulación de personas distintas: debe fallar por FK compuesta
-- y por trigger.
-- INSERT INTO voluntarios
--     (usuario_id, postulacion_id, disponibilidad, zona_preferencia)
-- VALUES (:usuario_a_id, :postulacion_del_usuario_b_id,
--         'Fines de semana', 'Zona de prueba');
--
-- J. Tercera visita para el mismo seguimiento: debe fallar.
-- INSERT INTO visitas_seguimiento
--     (seguimiento_id, voluntario_id, fecha_programada)
-- VALUES (:seguimiento_con_dos_visitas_id, :voluntario_asignado_id, CURRENT_DATE);
--
-- K. Visita realizada antes de la fecha programada: debe fallar.
-- INSERT INTO visitas_seguimiento
--     (seguimiento_id, voluntario_id, fecha_programada, fecha_realizada, estado)
-- VALUES (:seguimiento_activo_id, :voluntario_asignado_id, CURRENT_DATE,
--         CURRENT_TIMESTAMP - INTERVAL '1 day', 'realizada');

-- Este archivo corresponde al esquema base/inicial. Para actualizaciones
-- posteriores en ambientes productivos se recomienda utilizar migraciones
-- versionadas.

-- ============================================
-- SEGURIDAD / INTEGRIDAD — DESPLIEGUE LARAVEL
-- ============================================
-- Laravel debe conectarse con un rol de PostgreSQL sin privilegios de
-- superusuario y únicamente con los permisos requeridos por la aplicación.
-- Las credenciales deben mantenerse fuera del código fuente; producción y
-- desarrollo deben utilizar credenciales separadas.
