<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::statement('CREATE EXTENSION IF NOT EXISTS citext');

        DB::unprepared(<<<'SQL'
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo CITEXT NOT NULL,
    telefono VARCHAR(20),
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'ciudadano',
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified_at TIMESTAMPTZ NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_correo_unico UNIQUE (correo),
    CONSTRAINT usuarios_correo_no_vacio
        CHECK (btrim(correo::text) <> ''),
    CONSTRAINT usuarios_password_no_vacio
        CHECK (btrim(password) <> ''),
    -- SEGURIDAD / INTEGRIDAD: el teléfono es opcional, pero no puede ser solo espacios.
    CONSTRAINT usuarios_telefono_no_vacio
        CHECK (telefono IS NULL OR btrim(telefono) <> ''),
    CONSTRAINT usuarios_rol_valido
        CHECK (rol IN ('administrador', 'voluntario', 'ciudadano')),

    -- CORRECCIÓN: evita nombres/apellidos en blanco (NOT NULL no lo evita)
    CONSTRAINT usuarios_nombres_no_vacio
        CHECK (btrim(nombres) <> ''),
    CONSTRAINT usuarios_apellidos_no_vacio
        CHECK (btrim(apellidos) <> '')
);
SQL);

        DB::unprepared(<<<'SQL'
CREATE TABLE password_reset_tokens (
    email VARCHAR(255) PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NULL
);

CREATE TABLE sessions (
    id VARCHAR(255) PRIMARY KEY,
    user_id BIGINT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

CREATE INDEX sessions_user_id_index ON sessions(user_id);
CREATE INDEX sessions_last_activity_index ON sessions(last_activity);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS sessions');
        DB::statement('DROP TABLE IF EXISTS password_reset_tokens');
        DB::statement('DROP TABLE IF EXISTS usuarios');
    }
};

