<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE fotos_mascota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    mascota_id BIGINT NOT NULL
        REFERENCES mascotas(id)
        ON DELETE CASCADE,

    tipo VARCHAR(10) NOT NULL DEFAULT 'foto',

    url VARCHAR(255) NOT NULL,

    es_principal BOOLEAN NOT NULL DEFAULT FALSE,

    orden SMALLINT NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fotos_mascota_tipo_valido
        CHECK (tipo IN ('foto', 'video')),

    CONSTRAINT fotos_mascota_url_no_vacia
        CHECK (btrim(url) <> ''),

    CONSTRAINT fotos_mascota_orden_valido
        CHECK (orden > 0),

    -- Un video no puede ser la imagen principal.
    CONSTRAINT fotos_mascota_principal_solo_foto
        CHECK (tipo = 'foto' OR es_principal = FALSE)
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS fotos_mascota');
    }
};

