<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE postulaciones_voluntariado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT preserva el historial de postulaciones y revisiones.
    usuario_id BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    motivacion TEXT NOT NULL,
    habilidades TEXT,
    disponibilidad VARCHAR(150) NOT NULL,
    zona_preferencia VARCHAR(100) NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    comentarios_admin TEXT,

    revisado_por BIGINT
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,
    revisado_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT postulaciones_estado_valido
        CHECK (estado IN ('pendiente', 'aprobada', 'rechazada', 'cancelada')),

    -- Aprobada/rechazada exigen quién y cuándo revisó; cancelada la hace
    -- el propio ciudadano y no requiere revisión administrativa.
    CONSTRAINT postulaciones_revision_valida
        CHECK (
            (estado = 'pendiente'
             AND revisado_por IS NULL AND revisado_at IS NULL)
            OR
            (estado IN ('aprobada', 'rechazada')
             AND revisado_por IS NOT NULL AND revisado_at IS NOT NULL)
            OR
            (estado = 'cancelada'
             AND revisado_por IS NULL AND revisado_at IS NULL)
        ),

    CONSTRAINT postulaciones_motivacion_no_vacia CHECK (btrim(motivacion) <> ''),
    CONSTRAINT postulaciones_disponibilidad_no_vacia CHECK (btrim(disponibilidad) <> ''),
    CONSTRAINT postulaciones_zona_no_vacia CHECK (btrim(zona_preferencia) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS postulaciones_voluntariado');
    }
};

