<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE incidencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seguimiento_id BIGINT NOT NULL
        REFERENCES seguimientos_adopcion(id)
        ON DELETE RESTRICT,

    visita_id BIGINT
        REFERENCES visitas_seguimiento(id)
        ON DELETE RESTRICT,

    reportado_por BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    tipo VARCHAR(30) NOT NULL,
    descripcion TEXT NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    comentarios_resolucion TEXT,
    atendida_por BIGINT
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,
    atendida_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT incidencias_tipo_valido
        CHECK (tipo IN ('salud', 'maltrato', 'perdida_contacto', 'otro')),

    CONSTRAINT incidencias_estado_valido
        CHECK (estado IN ('pendiente', 'en_proceso', 'atendida')),

    CONSTRAINT incidencias_resolucion_valida
        CHECK (
            (estado = 'atendida'
             AND comentarios_resolucion IS NOT NULL
             AND atendida_por IS NOT NULL
             AND atendida_at IS NOT NULL)
            OR
            (estado IN ('pendiente', 'en_proceso')
             AND atendida_por IS NULL
             AND atendida_at IS NULL)
        ),

    CONSTRAINT incidencias_fecha_atencion_valida
        CHECK (atendida_at IS NULL OR atendida_at >= created_at),

    -- CORRECCIÓN: evita descripción/comentario de resolución en blanco
    CONSTRAINT incidencias_descripcion_no_vacia
        CHECK (btrim(descripcion) <> ''),
    CONSTRAINT incidencias_comentarios_resolucion_no_vacio
        CHECK (comentarios_resolucion IS NULL OR btrim(comentarios_resolucion) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS incidencias');
    }
};

