<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE voluntarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usuario_id BIGINT NOT NULL UNIQUE
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    postulacion_id BIGINT NOT NULL UNIQUE,

    habilidades TEXT,
    disponibilidad VARCHAR(150) NOT NULL,
    zona_preferencia VARCHAR(100) NOT NULL,

    estado VARCHAR(20) NOT NULL DEFAULT 'activo',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT voluntarios_estado_valido
        CHECK (estado IN ('activo', 'inactivo')),

    CONSTRAINT voluntarios_disponibilidad_no_vacia CHECK (btrim(disponibilidad) <> ''),
    CONSTRAINT voluntarios_zona_no_vacia CHECK (btrim(zona_preferencia) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS voluntarios');
    }
};

