<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(100) NOT NULL,
    especie VARCHAR(50) NOT NULL,                   -- FILTRO (solo perro/gato)
    raza VARCHAR(100),                              -- INFORMATIVO (NO FILTRO)
    edad SMALLINT NOT NULL CHECK (edad >= 0),       -- FILTRO (con rangos) — CORRECCIÓN: ahora obligatoria
    sexo VARCHAR(10) NOT NULL,                      -- FILTRO
    color VARCHAR(50),                              -- INFORMATIVO (NO FILTRO)
    tamano VARCHAR(20) NOT NULL,                    -- FILTRO
    descripcion TEXT,

    estado VARCHAR(20) NOT NULL DEFAULT 'borrador',

    -- RESTRICT conserva la trazabilidad de quién registró la mascota.
    registrado_por BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT mascotas_sexo_valido
        CHECK (sexo IN ('macho', 'hembra')),

    CONSTRAINT mascotas_estado_valido
        CHECK (estado IN ('borrador', 'disponible', 'adoptada')),

    CONSTRAINT mascotas_tamano_valido
        CHECK (tamano IN ('pequeno', 'mediano', 'grande')),

    -- CORRECCIÓN: el sistema solo maneja perros y gatos
    CONSTRAINT mascotas_especie_valida
        CHECK (especie IN ('perro', 'gato')),

    -- CORRECCIÓN: evita nombre de mascota en blanco
    CONSTRAINT mascotas_nombre_no_vacio
        CHECK (btrim(nombre) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS mascotas');
    }
};

