<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE visitas_seguimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT preserva el historial de visitas e incidencias.
    seguimiento_id BIGINT NOT NULL
        REFERENCES seguimientos_adopcion(id)
        ON DELETE RESTRICT,

    voluntario_id BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    fecha_programada DATE NOT NULL,
    fecha_realizada TIMESTAMPTZ,

    observaciones TEXT,
    estado_salud VARCHAR(50),
    foto_url VARCHAR(255),

    estado VARCHAR(20) NOT NULL DEFAULT 'programada',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT visitas_estado_valido
        CHECK (estado IN ('programada', 'realizada', 'no_asistio')),

    CONSTRAINT visitas_fecha_realizada_valida
        CHECK (
            (estado = 'realizada' AND fecha_realizada IS NOT NULL)
            OR
            (estado IN ('programada', 'no_asistio') AND fecha_realizada IS NULL)
        ),

    -- CORRECCIÓN: una visita no puede realizarse antes de su fecha programada
    CONSTRAINT visitas_cronologia_valida
        CHECK (fecha_realizada IS NULL OR fecha_realizada::date >= fecha_programada),

    -- SEGURIDAD / INTEGRIDAD: una foto opcional, si se informa, debe tener URL.
    CONSTRAINT visitas_foto_url_no_vacia
        CHECK (foto_url IS NULL OR btrim(foto_url) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS visitas_seguimiento');
    }
};

