<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE solicitudes_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT preserva el historial de solicitudes y su solicitante.
    solicitante_id BIGINT NOT NULL
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    mascota_id BIGINT NOT NULL
        REFERENCES mascotas(id)
        ON DELETE RESTRICT,

    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente',

    -- Información proporcionada por el ciudadano en el formulario
    tiene_otras_mascotas BOOLEAN NOT NULL,
    viven_otras_personas BOOLEAN NOT NULL,
    tiene_espacio_adecuado BOOLEAN NOT NULL,
    zona_aproximada VARCHAR(100) NOT NULL,
    horario_preferido VARCHAR(150) NOT NULL,
    comentarios_solicitante TEXT,
    declara_informacion_veraz BOOLEAN NOT NULL,

    -- Información interna del administrador
    comentarios_admin TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT solicitudes_estado_valido
        CHECK (estado IN (
            'pendiente',
            'en_espera',
            'aceptada',
            'rechazada',
            'cancelada',
            'cerrada'
        )),

    CONSTRAINT solicitud_declaracion_veraz_valida
        CHECK (declara_informacion_veraz = TRUE),

    -- CORRECCIÓN: evita zona/horario en blanco
    CONSTRAINT solicitudes_zona_no_vacia
        CHECK (btrim(zona_aproximada) <> ''),
    CONSTRAINT solicitudes_horario_no_vacio
        CHECK (btrim(horario_preferido) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS solicitudes_adopcion');
    }
};

