<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE seguimientos_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- RESTRICT: una adopción aceptada no pierde su seguimiento histórico.
    solicitud_id BIGINT NOT NULL UNIQUE
        REFERENCES solicitudes_adopcion(id)
        ON DELETE RESTRICT,

    voluntario_id BIGINT
        REFERENCES usuarios(id)
        ON DELETE RESTRICT,

    estado VARCHAR(20) NOT NULL DEFAULT 'sin_asignar',

    zona_aproximada VARCHAR(100) NOT NULL,
    horario_preferido VARCHAR(150) NOT NULL,

    fecha_inicio TIMESTAMPTZ,
    fecha_cierre TIMESTAMPTZ,
    observaciones_cierre TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT seguimientos_estado_valido
        CHECK (estado IN ('sin_asignar', 'activo', 'cerrado')),

    CONSTRAINT seguimientos_asignacion_valida
        CHECK (
            (estado = 'sin_asignar'
             AND voluntario_id IS NULL
             AND fecha_inicio IS NULL
             AND fecha_cierre IS NULL)
            OR
            (estado = 'activo'
             AND voluntario_id IS NOT NULL
             AND fecha_inicio IS NOT NULL
             AND fecha_cierre IS NULL)
            OR
            (estado = 'cerrado'
             AND voluntario_id IS NOT NULL
             AND fecha_inicio IS NOT NULL
             AND fecha_cierre IS NOT NULL)
        ),

    CONSTRAINT seguimientos_fechas_validas
        CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_inicio),

    -- CORRECCIÓN: evita zona/horario en blanco
    CONSTRAINT seguimientos_zona_no_vacia
        CHECK (btrim(zona_aproximada) <> ''),
    CONSTRAINT seguimientos_horario_no_vacio
        CHECK (btrim(horario_preferido) <> '')
);
SQL);
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS seguimientos_adopcion');
    }
};

